# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
#  pod 'NVActivityIndicatorView', '~> 5.1'
  pod 'Kingfisher'
  # Pods for ImageApp
  pod 'CCBottomRefreshControl'

end
