disabled_rules:
 - trailing_whitespace
 - type_body_length
 - file_length
excluded:
 - Pods
 - /Users/a12345/Projects/Platform/Platform/Platform/Managers/API/Models/OffensiveWords.swift
line_length:
 - 200 # warning
 - 250 # error
identifier_name:
 min_length:
   warning: 2
